sources:
  - type: http
    name: weather
    url: https://api.open-meteo.com/v1/forecast?latitude=43.826921,&longitude=-111.781215&current=temperature_2m,wind_speed_10m&hourly=temperature_2m,relative_humidity_2m,wind_speed_10m&temperature_unit=fahrenheit

  - type: file
    name: gadgets
    path: "./config/Gadgets Temperature Data.csv"

  # - type: http
  #   name: byui
  #   url: https://www.byui.edu/speeches/announcement-ricks-college-to-become-byu-idaho
  #   format: html

variables:
  average_temp: 0

tasks:
  - source: weather
    name: avg_temp
    output: average_temp
    steps:
      - type: json_query
        query: /hourly/temperature_2m
      - type: math
        operation: average
        decimals: 2

  - source: gadgets
    name: gadgets_json
    steps:
      - type: convert
        from: csv
      - type: loop
        body:
          - type: condition
            condition: "{{average_temp}} >= {{item.min_temperature}} && {{average_temp}} <= {{item.max_temperature}}"
            true_steps:
              - type: add_field
                field: "can_handle_temperature"
                value: true
            false_steps:
              - type: add_field
                field: "can_handle_temperature"
                value: false

outputs:
  - type: file
    path: ./config/results.json
    format: json
