[package]
name = "runners"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.9"
config = { path = "../config" }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
serde_yaml = "0.9.34"
csv = "1.3.1"
